feat: add InitRequiredForNotNullAttribute
allegro/dotnet-sdk pull request #5
Opened 2023-01-26 16:51 UTC by rafalschmidt97

2023-01-26 16:58 UTC, rafalschmidt97 commented on src/Allegro.DotnetSdk/Sdk/Sdk.props
> +            <IncludeAssets>runtime; compile; build; native; contentfiles; analyzers</IncludeAssets>
`compile` dodany celowo

Bez niego strzela assembly

<img width="771" alt="image" src="https://user-images.githubusercontent.com/14861637/214899548-34a8b882-9220-4215-940a-5d230df77f11.png">

2023-01-27 07:41 UTC, aszczepanski-allegro commented on src/Allegro.DotnetSdk/Sdk/Sdk.props
> +    <ItemGroup Label="NRT configuration" Condition=" '$(Configuration)' == 'Debug' AND '$(Nullable)' == 'enable' AND '$(AllegroDotnetSdkEnableSmartAnalyzers)' != false ">
`'$(Configuration)' == 'Debug'` jest tutaj konieczne? Wtedy zgaduję, że na build agentach się domyślnie nie odpali, więc jest ryzyko, że ktoś wrzuci kod który nie będzie się budował lokalnie

2023-01-27 07:44 UTC, aszczepanski-allegro commented
Dodałbym opis PRa - chociażby link do changeloga w `CSharpExtensions` (https://github.com/cezarypiatek/CSharpExtensions/releases/tag/4.2.8)

2023-01-27 07:46 UTC, aszczepanski-allegro commented
Wygląda, że jeszcze musisz podbić wersję paczki:
https://github.com/allegro/dotnet-sdk/blob/57f28fbee88241d2fb96dbd27b8602d443ca9e7b/src/Allegro.DotnetSdk/Allegro.DotnetSdk.csproj#L11

2023-01-27 07:47 UTC, aszczepanski-allegro requested changes
Wygląda ogólnie OK, dodałem drobne komentarze

2023-01-27 14:36 UTC, aszczepanski-allegro approved these changes

2023-01-27 14:48 UTC, merged